"""Added ForienKey into Analytics model

Revision ID: 0d2994e7ba31
Revises: 02f0f35d2c3b
Create Date: 2025-02-24 17:20:43.361779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2994e7ba31'
down_revision = '02f0f35d2c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'file_upload', ['file_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('file_id')

    # ### end Alembic commands ###
