"""Make file_id optional

Revision ID: 906eeb06f70f
Revises: 0d2994e7ba31
Create Date: 2025-02-25 13:37:45.575921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906eeb06f70f'
down_revision = '0d2994e7ba31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_data', schema=None) as batch_op:
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_data', schema=None) as batch_op:
        batch_op.alter_column('file_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
