"""Initial migrate

Revision ID: 9ea73a902991
Revises: 
Create Date: 2025-02-03 12:30:19.558554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ea73a902991'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=155), nullable=False),
    sa.Column('user_id', sa.String(length=175), nullable=False),
    sa.Column('college', sa.String(length=175), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('submodule', sa.String(length=100), nullable=True),
    sa.Column('time', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('file_upload',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=100), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_upload')
    op.drop_table('analytics_data')
    # ### end Alembic commands ###
