"""optional_college_location

Revision ID: 9ebbbc18eb11
Revises: 906eeb06f70f
Create Date: 2026-06-18 17:40:58.770357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebbbc18eb11'
down_revision = '906eeb06f70f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_data', schema=None) as batch_op:
        batch_op.alter_column('college',
               existing_type=sa.VARCHAR(length=175),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics_data', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('college',
               existing_type=sa.VARCHAR(length=175),
               nullable=False)

    # ### end Alembic commands ###
